version: "3.9"

services:
    postgres:
        image: postgres:13
        container_name: postgres
        hostname: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
            POSTGRES_USER: ${POSTGRES_USER:-admin_sa}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin8520}
            POSTGRES_DB: ${POSTGRES_DB:-admin_db}
        volumes:
            - ./initialize-database.sh:/docker-entrypoint-initdb.d/initdb.sh
        profiles:
            - backend
            - all
    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin
        ports:
            - "80:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin8520}
        volumes:
            - ./servers.json:/pgadmin4/servers.json
        depends_on:
            - "postgres"
        profiles:
            - frontend
            - all